#!/bin/bash
#
# pkgsyncremove - Elimina un nombre de paquete de los ficheros pkgsync
# 2020 Esteban M. Navas Martín <algodelinux@gmail.com>.
#

# Obtener los parámetros pasados al script
if [ -z $1 ] || [ -z $2 ]; then
   echo "Sintaxis: $0 [paquete] [fichero] [tipo-maquina] [tipo-fichero]"
   echo "   tipos de máquinas: workstation, siatic, infolab, notebook, notebookHP,..."
   echo "   tipos de ficheros: musthave, mayhave, maynothave."

   exit 1
fi

paquete=$1
fichero=$2

# Obtener los directorios de módulos
modulepaths=$(puppet config print modulepath)

# Dividir el string por el delimitador ':'
IFS=:
strmodulepaths=($modulepaths)

for modulepath in "${strmodulepaths[@]}"; do
  pkgsyncfiles="$(echo -e "${modulepath}" | tr -d '[:space:]')""/pkgsync/files"

  # Si existe pkgsync en el directorio de módulos, insertamos el paquete en el fichero solicitado
  if [ -d $pkgsyncfiles ]; then
     if [ -n $3 ]; then
        if [ -n $4 ]; then
           encontrados=$(find $pkgsyncfiles/$3 -path "*$4*" -type f -name $fichero)
        else
           encontrados=$(find $pkgsyncfiles/$3 -type f -name $fichero)
        fi
     else
        encontrados=$(find $pkgsyncfiles -type f -name $fichero)
     fi

     IFS=$'\n'
     strencontrados=($encontrados)

     for encontrado in "${strencontrados[@]}"; do
        find $pkgsyncfiles -type f -wholename $encontrado -exec sed -i "s|${paquete}||g" {} \; -exec sort -o {} -u {} \; -exec sed -i '/^$/d' {} \;
     done
  fi
done

